"""add analytics fields to links

Revision ID: 965da3fe008b
Revises: 5d87f22890c7
Create Date: 2026-06-23 19:37:58.308235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "965da3fe008b"
down_revision: Union[str, Sequence[str], None] = "5d87f22890c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "links",
        sa.Column("click_count", sa.Integer(), server_default="0", nullable=False),
    )

    op.add_column(
        "links",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.add_column(
        "links",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.add_column(
        "links",
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "last_accessed_at")
    op.drop_column("links", "updated_at")
    op.drop_column("links", "created_at")
    op.drop_column("links", "click_count")
    # ### end Alembic commands ###
